# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'BigCityHunt' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for BigCityHunt
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'GoogleSignIn'

  # pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

end
